version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=job-board
    ports:
      - '$DB_PORT:$DB_PORT'
    container_name: job-board-backend
    volumes:
      - psql_data:/var/lib/postgresql/data
  app:
    depends_on:
      - postgresdb
    build: .
    restart: always
    env_file: .env
    ports:
      - 5000:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    links:
      - postgresdb
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local
  psql_data:
